name: zam_event_bus
version: 0.7.0
description: Event bus is a event based state management package for dart.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_event_bus

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  zam_command_pattern: ^0.2.0
  zam_core: ^0.6.0

dev_dependencies:
  lints: ^1.0.1
  zam_test: ^0.4.0
