name: zam_event_bus
version: 0.2.0
description: Event bus is a event based state management package for dart.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_event_bus

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  zam_command_pattern: ^0.1.0
  zam_core: ^0.5.0

dev_dependencies:
  zam_test: ^0.3.0
